### ISSUE TITLE
Image Upscaler HALTED | Improper import statement for dependency: `basicsr` | ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

### ISSUE THREAD

**Issue by Daethyra** [Daethyra/FreeStream#64]
#### Reference Issues:
1) [BasicSR](https://github.com/XPixelGroup/BasicSR/issues/663 "base repository which should receive the fix")
2) [Real-ESRGAN](https://github.com/xinntao/Real-ESRGAN/issues/765 "duplicate issue for realesrgan")
3) [Automatic1111](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985 "duplicate issue for automatic1111")

#### My Traceback (PII Scrubbed):
```PowerShell
(.venv) PS C:\Users\Software\testground\Real-ESRGAN> python .\inference_realesrgan.py      
Traceback (most recent call last):
 File "C:\Users\Software\testground\Real-ESRGAN\inference_realesrgan.py", line 5, in <module>
    from basicsr.archs.rrdbnet_arch import RRDBNet
 File "C:\Users\Software\.venv\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
 File "C:\Users\Software\.venv\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
 File "C:\Users\Software\.venv\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
 File "C:\Users\Software\.venv\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
 File "C:\Users\Software\.venv\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'
```

#### Suggested Fix
- [Link](https://github.com/xinntao/Real-ESRGAN/issues/765#issuecomment-1998507898)
![2024-03-16 11_35_39-ModuleNotFoundError_ No module named 'torchvision transforms functional_tensor' ](https://github.com/Daethyra/FreeStream/assets/109057945/4b00bcb1-d0fa-4e33-bb6d-67c61efb7258)
- [Link](https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/13985#issuecomment-2001988810)
![2024-03-16 11_38_59- Bug _ ModuleNotFoundError_ No module named 'torchvision transforms functional_t](https://github.com/Daethyra/FreeStream/assets/109057945/d43f23eb-bc11-45fb-9673-735e6b66e33a)

**Comment by Daethyra** [comment]
Fixed and finished w/ #77
